export const environment = {
    PRODUCTION: true,
    HIDE_ROUTES: true,
    FSS_API_URL: "ENV_FSS_API_URL",
    KEYCLOAK_URL: "ENV_KEYCLOAK_URL",
    KEYCLOAK_REALM: "ENV_KEYCLOAK_REALM",
    KEYCLOAK_CLIENT_ID: "ENV_KEYCLOAK_CLIENT_ID",
    KEYCLOAK_CLIENT_SECRET: "ENV_KEYCLOAK_CLIENT_SECRET",
};
